local addon = {}
assert(loadfile("Runs.lua"))("DungeonLootTracker", addon)
local db = {}
addon.Initialize(db)
local dungeon = {name="Dungeon", instanceID=1, instanceType="party", difficultyID=2, difficultyName="Heroic"}
local raid = {name="Raid", instanceID=2, instanceType="raid", difficultyID=14, difficultyName="Normal"}
addon.UpdateInstance(nil, 1)
assert(#db.runs == 0)
addon.UpdateInstance(dungeon, 10)
addon.RecordLoot("Item x2", 11)
addon.UpdateInstance(dungeon, 12)
assert(#db.runs == 1 and db.runs[1].enteredAt == 10 and #db.runs[1].loot == 1)
-- Reload resumes the same run, with the saved index rather than table aliases.
addon.Initialize(db)
addon.UpdateInstance(dungeon, 13, false)
assert(#db.runs == 1)
addon.UpdateInstance(nil, 20)
assert(db.runs[1].leftAt == 20 and db.runs[1].endReason == "left")
addon.RecordLoot("Outdoor loot", 21)
assert(#db.runs[1].loot == 1)
addon.UpdateInstance(raid, 30)
addon.RecordLoot("Raid loot", 31)
assert(db.runs[2].instanceType == "raid" and #db.runs[2].loot == 1)
assert(addon.Stop(32))
addon.UpdateInstance(raid, 33)
addon.RecordLoot("Ignored", 34)
assert(#db.runs == 2 and #db.runs[2].loot == 1)
addon.UpdateInstance(nil, 40)
assert(db.runs[2].leftAt == 40 and db.runs[2].endedAt == 32)
addon.UpdateInstance(dungeon, 50)
addon.Checkpoint(55)
addon.UpdateInstance(nil, 80, true)
assert(db.runs[3].leftAt == nil and db.runs[3].endedAt == 55)
assert(db.runs[3].endReason == "interrupted")
addon.UpdateInstance(dungeon, 90)
addon.UpdateInstance(raid, 100)
assert(db.runs[4].leftAt == 100 and db.runs[5].enteredAt == 100)
local heroicRaid = {name="Raid", instanceID=2, instanceType="raid", difficultyID=15, difficultyName="Heroic"}
addon.UpdateInstance(heroicRaid, 110)
assert(db.runs[5].leftAt == 110 and db.runs[6].difficultyID == 15)
print("Run lifecycle tests passed")
